Mb dev
omicsr/dgapaq pull request #5
Opened 2021-03-12 07:59 UTC by mboissel

main change : add bcftool cmd to filter chr at the vcf level
fix merge list vcf problem with big list : loop on batch
fix sort always needed for vcf
add option to not remove tmp folder

2021-03-12 08:10 UTC, mcanouil requested changes
Please fix the comments and ensure code style is similar to the overall code.
Call to `system()ˋ should be avoided as much as possible, especially when there is an R API/function.

2021-03-12 08:10 UTC, mcanouil commented on R/check_genotype.R
> +          # system(paste("cp", ivcf, iout))
Use file.copy

2021-03-12 08:10 UTC, mcanouil commented on R/check_genotype.R
> +        file = file.path(output_tmp_dir, paste0("list_vcf",i,".txt")),
Spaces after commas

2021-03-12 08:10 UTC, mcanouil commented on R/check_genotype.R
> +    if(nb_batch==1) {
Spaces

2021-03-12 08:10 UTC, mcanouil commented on R/check_genotype.R
> +  if(clean_tmp_folder) {unlink(output_tmp_dir, recursive = TRUE)}
Spaces and no braces

2021-03-12 08:10 UTC, mcanouil commented on R/compress_coverage.R
> +    bgzip2 = "bzip2"
(b)gzip is not bzip2.
Use bzfile and related function to handle bzip2 compressed files

2021-05-11 09:19 UTC, mcanouil commented
@mboissel Any news on this?

2021-05-11 09:27 UTC, mboissel commented
> @mboissel Any news on this?

Yes I've taken into account your several comments (indent, style and binary to use)

2021-09-15 21:57 UTC, closed without merging